# Site settings
name: Nic Borensztein
email: nic@nicbor.com
#canonical_url: https://nicbor.com
keywords: "Serial Entrepreneur, Founder Coach, Fractional CTO"
skills: "Engineering Leader based in San Francisco"
baseurl:
form_submit_url: https://formspree.io/f/xqkjpord
# for formatting the copyright notice, what year this site was published
published_year: 2022

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nicbor/
  - title: medium
    url: https://medium.com/@nicbor
  - title: twitter
    url: https://twitter.com/nicbor1
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  # 2c3d57 #285172
  # primary: 2196F3
  primary: 2c3d57
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
